plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'tr.edu.balikesir.anketrapor'
    compileSdk 35

    defaultConfig {
        applicationId 'tr.edu.balikesir.yerelajan'
        minSdk 31
        targetSdk 35
        versionCode 10
        versionName '1.0.4'
    }

    buildTypes {
        debug {
            debuggable false
            jniDebuggable false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    androidResources {
        noCompress += ['litertlm']
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'com.google.ai.edge.litertlm:litertlm-android:0.13.1'
}
